apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  selector:
    matchLabels:
      app: blissapp
  template:
    metadata:
      labels:
        app: blissapp
    spec:
      containers:
      - name: mywebapp
        image: chinnyb/bliss-web-app:latest
        resources:
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  selector:
    app: blissapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31500
